import {
  ArrowRight,
  ArrowUpRight,
  BookOpen,
  Check,
  ChevronRight,
  Clock3,
  Compass,
  ExternalLink,
  Flame,
  Gem,
  Heart,
  Layers,
  Menu,
  Search,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Swords,
  X,
  GitCompareArrows,
  CircleHelp,
  ArrowLeft,
  CheckCircle2,
} from 'lucide-react';
const icons = {
  ArrowRight,
  ArrowUpRight,
  BookOpen,
  Check,
  ChevronRight,
  Clock3,
  Compass,
  ExternalLink,
  Flame,
  Gem,
  Heart,
  Layers,
  Menu,
  Search,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Swords,
  X,
  GitCompareArrows,
  CircleHelp,
  ArrowLeft,
  CheckCircle2,
};
export function AppIcon({ name, size = 20, ...props }) {
  const Icon = icons[name] || BookOpen;
  return <Icon size={size} strokeWidth={1.65} aria-hidden="true" {...props} />;
}
